---
telegram:
  api_key: your-telegram-api-key
  admin_id:
    # egor
    - 653782769
    # ruslan
    - 64156944
  bot_name: Dark Logger
  enabled: false
openai:
  api_key: your-openai-api-key
  overseer_id: your-overseer-id
  consultant_id: your-logger-id
  calculator_id: your-calculator-id
  dev_prefix: Dev
save_path: your-path-to-imgs
mongo:
  enabled: false
  host: 127.0.0.1
  port: 27017
  user: admin
  password: pass
  database: evsys
  save_url: mongodb://admin:pass@
  expired_days: 7
prod-service:
  login: chatbot
  password: pass
  base_url: repository-url
instagram:
  enabled: false
  access_token: your-instagram-access-token
  verify_token: your-instagram-verify-token
  app_secret: your-instagram-app-secret
whatsapp:
  enabled: false
  access_token: your-whatsapp-access-token
  verify_token: your-whatsapp-verify-token
  app_secret: your-whatsapp-app-secret
  phone_number_id: your-whatsapp-phone-number-id
