---

telegram_api_key: your-telegram-api-key
openai:
  api_key: your-openai-api-key
  overseer_id: your-overseer-id
  consultant_id: your-logger-id
  dev_prefix: Dev
img_path: your-path-to-imgs
mongo:
  enabled: false
  host: 127.0.0.1
  port: 27017
  user: admin
  password: pass
  database: evsys
  save_url: mongodb://admin:pass@
  expired_days: 7
prod-service:
  login: chatbot
  password: pass
  base_url: repository-url