#name: Deploy to Digital Ocean Droplet

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare configuration file
        run: |
          sed -i 's|${TELEGRAM_API_KEY}|'"$TELEGRAM_API_KEY"'|g' darkcs-conf.yml
          sed -i 's|${LISTEN_PORT}|'"$LISTEN_PORT"'|g' darkcs-conf.yml
          sed -i 's|${API_KEY}|'"$API_KEY"'|g' darkcs-conf.yml
          sed -i 's|${OPENAI_API_KEY}|'"$OPENAI_API_KEY"'|g' darkcs-conf.yml
          sed -i 's|${OVERSEER_ID}|'"$OVERSEER_ID"'|g' darkcs-conf.yml
          sed -i 's|${CONSULTANT_ID}|'"$CONSULTANT_ID"'|g' darkcs-conf.yml
          sed -i 's|${CALCULATOR_ID}|'"$CALCULATOR_ID"'|g' darkcs-conf.yml
          sed -i 's|${MONGO_HOST}|'"$MONGO_HOST"'|g' darkcs-conf.yml
          sed -i 's|${MONGO_PORT}|'"$MONGO_PORT"'|g' darkcs-conf.yml
          sed -i 's|${MONGO_USER}|'"$MONGO_USER"'|g' darkcs-conf.yml
          sed -i 's|${MONGO_PASSWORD}|'"$MONGO_PASSWORD"'|g' darkcs-conf.yml
          sed -i 's|${MONGO_DATABASE}|'"$MONGO_DATABASE"'|g' darkcs-conf.yml
          sed -i 's|${REPO_LOGIN}|'"$REPO_LOGIN"'|g' darkcs-conf.yml
          sed -i 's|${REPO_PASSWORD}|'"$REPO_PASSWORD"'|g' darkcs-conf.yml
          sed -i 's|${REPO_BASE_URL}|'"$REPO_BASE_URL"'|g' darkcs-conf.yml
          sed -i 's|${SMART_API_KEY}|'"$SMART_API_KEY"'|g' darkcs-conf.yml
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          LISTEN_PORT: ${{ vars.LISTEN_PORT }}
          API_KEY: ${{ secrets.API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OVERSEER_ID: ${{ secrets.OVERSEER_ID }}
          CONSULTANT_ID: ${{ secrets.CONSULTANT_ID }}
          CALCULATOR_ID: ${{ secrets.CALCULATOR_ID }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          REPO_LOGIN: ${{ secrets.REPO_LOGIN }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
          REPO_BASE_URL: ${{ secrets.REPO_BASE_URL }}
          SMART_API_KEY: ${{ secrets.SMART_API_KEY }}

      - name: Copy Configuration to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "darkcs-conf.yml"
          target: "/etc/conf/"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build Go application
        run: |
          go build -v -o darkcs

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "darkcs"
          target: "/usr/local/bin/"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            systemctl restart darkcs.service
